# Site settings
title: Sonpro Blog
motto: 기록하는 공간... IT Engineer
email: isonpro@gmail.com
description: "생각하는 연습, 글쓰는 연습, 표현하는 연습."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sonpro.github.io" # the base hostname & protocol for your site
twitter_username: isonpro
github_username:  sonpro
disqus_shortname: sonpro
disqus_comment_username: sonpro
disqus_domain: "https://sonpro.github.io" # fixed
excerpt_separator: <!--more-->
encoding: utf-8


# Build settings
markdown: kramdown
# !github-pages! mandatory › https://help.github.com/articles/using-jekyll-with-pages/#configuration-settings-you-cannot-change
# Since Jekyll 3 the default highlighter is Rouge (replaced Pygments.rb in v44)
highlighter: rouge

# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html

kramdown:
  input: GFM
  syntax_highlighter: rouge
  #linenos: true
  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



permalink: /:categories/:title.html

gems :
     - jekyll-paginate

paginate: 10
paginate_path: "/page:num/"
